const yaml = require('js-yaml');
const fs   = require('fs');
const { mapType } = require('./typeMapper');

const contract = {
  packageId: '01da4dba66c232540ae7d1214cc22e32dc89c9f36c114c7f1dec959ce81b66ac',
  packageName: 'test-agreement',
  module: 'Agreement',
  template: 'MultiPartyAgreement',
  fields: [
    { name: 'proposer',        type: 'Party' },
    { name: 'signatories',     type: { List: 'Party' } },
    { name: 'requiredParties', type: { List: 'Party' } },
    { name: 'terms',           type: 'Text' },
  ],
  choices: [
    {
      name: 'AddParty',
      consuming: false,
      args: [{ name: 'newParty', type: 'Party' }],
      returns: { ContractId: 'MultiPartyAgreement' },
    },
    {
      name: 'Close',
      consuming: true,
      args: [],
      returns: 'Unit',
    },
  ],
};

const schemas = {};

const createProps = {};
const createRequired = [];
for (const f of contract.fields) {
  createProps[f.name] = mapType(f.type);
  createRequired.push(f.name);
}
schemas['MultiPartyAgreement_CreateArgs'] = {
  type: 'object',
  description: 'Fields required to create a MultiPartyAgreement contract',
  properties: createProps,
  required: createRequired,
};

schemas['MultiPartyAgreement_Contract'] = {
  type: 'object',
  description: 'An active MultiPartyAgreement contract on the ledger',
  properties: {
    contractId: { type: 'string', format: 'daml-contract-id' },
    templateId: { type: 'string', examples: ['#test-agreement:Agreement:MultiPartyAgreement'] },
    payload: { '$ref': '#/components/schemas/MultiPartyAgreement_CreateArgs' },
  },
  required: ['contractId', 'templateId', 'payload'],
};

for (const choice of contract.choices) {
  const props = {};
  for (const arg of choice.args) {
    props[arg.name] = mapType(arg.type);
  }
  schemas[`MultiPartyAgreement_Choice_${choice.name}`] = {
    type: 'object',
    description: `[${choice.consuming ? 'Consuming' : 'Non-consuming'}] Args for choice ${choice.name}`,
    properties: props,
    ...(choice.args.length > 0 ? { required: choice.args.map(a => a.name) } : {}),
  };
}

const paths = {};
const base = `/Agreement/MultiPartyAgreement`;

paths[`${base}/create`] = {
  post: {
    operationId: 'create_MultiPartyAgreement',
    summary: 'Create a MultiPartyAgreement contract',
    tags: ['Agreement'],
    requestBody: {
      required: true,
      content: { 'application/json': { schema: { '$ref': '#/components/schemas/MultiPartyAgreement_CreateArgs' } } },
    },
    responses: {
      '200': {
        description: 'Contract created',
        content: { 'application/json': { schema: { type: 'object', properties: {
          updateId: { type: 'string' },
          completionOffset: { type: 'integer' },
        }}}},
      },
    },
  },
};

paths[`${base}/query`] = {
  post: {
    operationId: 'query_MultiPartyAgreement',
    summary: 'Query active MultiPartyAgreement contracts',
    tags: ['Agreement'],
    requestBody: {
      required: true,
      content: { 'application/json': { schema: { type: 'object', required: ['activeAtOffset'], properties: {
        activeAtOffset: { type: 'integer', description: 'Get from /v2/state/ledger-end' },
      }}}},
    },
    responses: {
      '200': {
        description: 'List of active contracts',
        content: { 'application/json': { schema: { type: 'object', properties: {
          activeContracts: { type: 'array', items: { '$ref': '#/components/schemas/MultiPartyAgreement_Contract' } },
        }}}},
      },
    },
  },
};

for (const choice of contract.choices) {
  paths[`${base}/{contractId}/exercise/${choice.name}`] = {
    post: {
      operationId: `exercise_${choice.name}`,
      summary: `Exercise ${choice.name} on MultiPartyAgreement`,
      description: choice.consuming
        ? 'Consuming, this will archive the contract'
        : 'Non-consuming, contract stays active',
      tags: ['Agreement'],
      parameters: [{
        name: 'contractId', in: 'path', required: true,
        schema: { type: 'string', format: 'daml-contract-id' },
      }],
      requestBody: {
        required: true,
        content: { 'application/json': { schema: { '$ref': `#/components/schemas/MultiPartyAgreement_Choice_${choice.name}` } } },
      },
      responses: {
        '200': { description: `${choice.name} exercised successfully` },
        '404': { description: 'Contract not found or already archived' },
      },
    },
  };
}

const spec = {
  openapi: '3.1.0',
  info: {
    title: 'test-agreement Canton API',
    version: '1.3.0',
    description: `Auto-generated by Cast from test-agreement-1.3.0.dar\n\nPackage ID: \`${contract.packageId}\``,
  },
  servers: [{ url: 'http://localhost:7575', description: 'Canton JSON Ledger API' }],
  tags: [{ name: 'Agreement', description: 'MultiPartyAgreement template operations' }],
  paths,
  components: { schemas },
};

const output = yaml.dump(spec, { indent: 2, lineWidth: 120, noRefs: true });
fs.writeFileSync('openapi.yaml', output);

console.log('openapi.yaml generated!');
console.log(`   ${Object.keys(paths).length} endpoints`);
console.log(`   ${Object.keys(schemas).length} schemas`);
console.log('\nNext: paste openapi.yaml into https://editor.swagger.io');
